apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: openebs-cstor-k8s-basic
  annotations:
    openebs.io/cas-type: cstor
    cas.openebs.io/config: |
      - name: StoragePoolClaim
        value: "k8s-basic"
      - name: ReplicaCount
        value: "2"       
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete